version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: Thang@216102001
      DB_DATABASE: security

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Thang@216102001
      MYSQL_DATABASE: security
    ports:
      - "3306:3306"
