# Use the official MySQL image as the base image
FROM mysql:latest

# Set the root password for MySQL
ENV MYSQL_ROOT_PASSWORD=Thang@26102001

# Create a new database
ENV MYSQL_DATABASE=security

# Expose the port MySQL runs on
EXPOSE 3306
